from decouple import AutoConfig

dconfig = AutoConfig()

DATA_PREPARATION_DOCKER_IMAGE = dconfig("DATA_PREPARATION_DOCKER_IMAGE")
DATABASE_TYPE = dconfig("DATABASE_TYPE")
DATABASE_USER = dconfig("DATABASE_USER")
DATABASE_PASSWORD = dconfig("DATABASE_PASSWORD")
DATABASE_HOST = dconfig("DATABASE_HOST")
DATABASE_NAME = dconfig("DATABASE_NAME")
DATABASE_DRIVER = dconfig("DATABASE_DRIVER")
DATABASE_STRING = f"{DATABASE_TYPE}://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}?driver={DATABASE_DRIVER}"
PROJECT_DIR = dconfig("PROJECT_DIR")
GCP_PROJECT = dconfig("GCP_PROJECT")
URL_FILE =  dconfig("URL_FILE")
FILE_NAME_XLS =  dconfig("FILE_NAME_XLS")
FILE_NAME_CSV =  dconfig("FILE_NAME_CSV")
BUCKET_NAME =  dconfig("BUCKET_NAME")
MONTH = dconfig("MONTH")
YEAR = dconfig("YEAR")
SHEET_NAME = dconfig("SHEET_NAME")